# Generated by Django 3.1.4 on 2020-12-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_place_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='adress',
            new_name='address',
        ),
    ]
